import { db, pollsTable, pollOptionsTable, profilesTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(pollOptionsTable);
  await db.delete(pollsTable);
  await db.delete(profilesTable);

  // ── Profiles ────────────────────────────────────────────────────────────────
  const profiles = await db
    .insert(profilesTable)
    .values([
      {
        name: "Sara Al-Rashidi",
        headline: "Redefining venture capital in Saudi Arabia",
        role: "Managing Partner",
        company: "Wadi Ventures",
        sector: "Venture & Startups",
        country: "Saudi Arabia",
        city: "Riyadh",
        imageUrl: null,
        summary: "Sara Al-Rashidi is one of the most influential voices in the Saudi startup ecosystem, having backed over 40 early-stage founders across the region.",
        story: "When Sara left McKinsey to start her own fund in 2018, very few people believed a female-led VC could thrive in Riyadh. Today, her portfolio includes three unicorns and she sits on the boards of some of the region's most exciting companies. Her thesis is simple: bet on obsessed founders solving real regional problems.",
        lessonsLearned: [
          "The region's biggest opportunity is in solving problems that global funds ignore.",
          "Relationship-building is the real currency in MENA investing.",
          "Speed of decision-making is a competitive advantage — most regional funds are too slow.",
        ],
        quote: "We're not copying Silicon Valley. We're building something the region has never seen before.",
        isFeatured: true,
        isVerified: true,
        viewCount: 12400,
        associatedPollCount: 8,
      },
      {
        name: "Omar Khalil",
        headline: "The architect of Dubai's AI infrastructure play",
        role: "Co-Founder & CEO",
        company: "NeuralBridge",
        sector: "Technology & AI",
        country: "UAE",
        city: "Dubai",
        imageUrl: null,
        summary: "Omar is building the cloud and AI infrastructure layer that powers the UAE's Vision 2031 ambitions, with over $200M raised to date.",
        story: "A former Microsoft engineer who grew up in Alexandria, Omar saw an infrastructure gap in the region that no global cloud provider was solving. He moved to Dubai in 2019, raised a seed round in 90 days, and never looked back. NeuralBridge now employs 340 people across 8 countries.",
        lessonsLearned: [
          "Infrastructure is boring until it's not — then it's everything.",
          "Hire people who argue with you. Yes-men build mediocre companies.",
          "The Middle East's talent problem is a marketing problem. The talent exists.",
        ],
        quote: "Every nation that controls its own AI infrastructure will define its own future. That's why this matters.",
        isFeatured: true,
        isVerified: true,
        viewCount: 9800,
        associatedPollCount: 12,
      },
      {
        name: "Lina Mansour",
        headline: "Turning Jordan's creative economy into a global export",
        role: "Founder",
        company: "Studio Bilad",
        sector: "Media & Content",
        country: "Jordan",
        city: "Amman",
        imageUrl: null,
        summary: "Lina built Amman's most influential creative agency from a bedroom studio to a 60-person team producing content for brands across 14 countries.",
        story: "Lina started Studio Bilad with $3,000 and a camera she saved for two years to buy. She believed that Arab storytelling deserved world-class production values. Five years later, her studio has won 22 regional awards and her content has been watched over 800 million times across platforms.",
        lessonsLearned: [
          "Authenticity is the only differentiator that doesn't expire.",
          "Never apologize for creating in Arabic. It's your biggest advantage, not your limitation.",
          "The diaspora is your distribution network. Use it.",
        ],
        quote: "We're not 'emerging.' We've been here. The world is finally looking.",
        isFeatured: true,
        isVerified: true,
        viewCount: 8200,
        associatedPollCount: 5,
      },
      {
        name: "Khalid Al-Faraj",
        headline: "Saudi Arabia's most debated leadership voice",
        role: "CEO",
        company: "Mawjoud Group",
        sector: "Leadership",
        country: "Saudi Arabia",
        city: "Jeddah",
        imageUrl: null,
        summary: "Khalid has built one of the GCC's largest family business conglomerates while being one of the most outspoken voices on leadership reform in the Arab world.",
        story: "Inheriting a struggling family business at 28, Khalid transformed it into a 14-company group over 15 years. He's now one of the loudest advocates for professionalizing Arab family businesses and breaking the culture of nepotism that he says held back the region for decades.",
        lessonsLearned: [
          "Merit must win over loyalty — in family businesses and in nations.",
          "Your reputation is built in the downturns, not the booms.",
          "Leaders who don't read are managing on borrowed time.",
        ],
        quote: "The Arab world has incredible ambition and terrible systems. Fix the systems.",
        isFeatured: false,
        isVerified: true,
        viewCount: 7100,
        associatedPollCount: 9,
      },
      {
        name: "Nora Hamdan",
        headline: "Making fintech accessible to 100M underbanked Arabs",
        role: "Co-Founder & COO",
        company: "Fulus",
        sector: "Finance",
        country: "Egypt",
        city: "Cairo",
        imageUrl: null,
        summary: "Nora co-founded Fulus to bring financial inclusion to the 100 million Arabs without bank accounts, raising $45M Series B in 2025.",
        story: "Growing up watching her parents struggle with the informal money economy, Nora always believed that access to basic financial services was a right, not a privilege. She studied economics in Cairo, got an MBA in London, and returned home with a mission. Fulus now serves 2.3 million users across Egypt and Jordan.",
        lessonsLearned: [
          "The biggest market opportunity in MENA is the one that global VCs can't underwrite.",
          "Regulatory relationships are a competitive moat, not a burden.",
          "Trust is the product when you're serving people who've been failed by institutions.",
        ],
        quote: "Financial exclusion is a policy choice. So is inclusion.",
        isFeatured: false,
        isVerified: true,
        viewCount: 6300,
        associatedPollCount: 6,
      },
      {
        name: "Tariq Al-Sayed",
        headline: "Building Qatar's quantum computing ecosystem",
        role: "Chief Scientist",
        company: "Qatar Computing Research Institute",
        sector: "Technology & AI",
        country: "Qatar",
        city: "Doha",
        imageUrl: null,
        summary: "Tariq leads QCRI's flagship quantum initiative and has published 87 papers that are shaping how the Middle East approaches deep tech.",
        story: "Tariq was the first Qatari to complete a PhD in quantum computing. He turned down offers from IBM and Google to return to Doha, believing that the Gulf needed its own research IP, not just licensing deals. He's now building a team of 120 researchers and training the next generation of Arab scientists.",
        lessonsLearned: [
          "The region's brain drain is a story we tell ourselves. The talent returns if the opportunity is real.",
          "Publish or perish is for academics. Build or perish is for us.",
          "Basic research is infrastructure. Stop treating it like a luxury.",
        ],
        quote: "Nations that don't invest in curiosity will always buy the future from those who do.",
        isFeatured: false,
        isVerified: true,
        viewCount: 5800,
        associatedPollCount: 4,
      },
      {
        name: "Maya Rifai",
        headline: "The Lebanese entrepreneur rebuilding from zero",
        role: "Founder",
        company: "Zaman",
        sector: "Retail & Consumer",
        country: "Lebanon",
        city: "Beirut",
        imageUrl: null,
        summary: "Maya launched Zaman in the aftermath of the Beirut explosion, creating a sustainable lifestyle brand that ships to 40 countries.",
        story: "Maya lost her apartment, her office, and her first business in the 2020 Beirut explosion. Six months later, she launched Zaman from a co-working space with $8,000 in savings. What started as handmade Lebanese crafts has evolved into a global brand that celebrates Arab craft traditions with modern design sensibility.",
        lessonsLearned: [
          "Crisis reveals what actually matters in a business model.",
          "Diaspora customers are your most loyal — they're buying identity, not just products.",
          "Don't wait for stability. Build despite the chaos.",
        ],
        quote: "Beirut has been rebuilt seven times. This is just the eighth.",
        isFeatured: false,
        isVerified: true,
        viewCount: 5200,
        associatedPollCount: 3,
      },
      {
        name: "Ahmed Al-Balushi",
        headline: "Oman's most ambitious climate entrepreneur",
        role: "Co-Founder & CEO",
        company: "GreenGulf Energy",
        sector: "Energy",
        country: "Oman",
        city: "Muscat",
        imageUrl: null,
        summary: "Ahmed is building the Gulf's first vertically integrated green hydrogen company, backed by sovereign funds from three GCC nations.",
        story: "Ahmed spent 10 years at Shell before deciding he could do more outside. He raised $120M to build the infrastructure that will eventually power the decarbonization of Gulf industry. His bet is that Oman's geography and sunlight make it the ideal hub for green hydrogen exports to Europe by 2030.",
        lessonsLearned: [
          "Energy transition in the Gulf is not idealism — it's economics. Follow the money.",
          "Sovereign fund backing changes everything: speed, credibility, distribution.",
          "The cleanest thing you can do is be honest about timelines.",
        ],
        quote: "We built our wealth on oil. We'll build our future on sunshine.",
        isFeatured: false,
        isVerified: false,
        viewCount: 4100,
        associatedPollCount: 2,
      },
    ])
    .returning();

  console.log(`Inserted ${profiles.length} profiles`);

  // ── Polls ────────────────────────────────────────────────────────────────────
  const pollData = [
    {
      question: "Will Dubai remain the #1 startup hub in the Middle East by 2030?",
      context: "Riyadh has been making massive moves with Vision 2030 funding, while Abu Dhabi is positioning itself as a deep-tech capital. Dubai's lead feels less certain.",
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: ["Dubai", "Riyadh", "Startups", "Vision 2030"],
      pollType: "binary",
      isFeatured: true,
      isEditorsPick: true,
      options: ["Yes, Dubai's ecosystem is too established to overtake", "No, Riyadh will surpass it within 5 years"],
      votes: [2840, 1920],
    },
    {
      question: "Is the region's biggest talent problem a supply problem or a retention problem?",
      context: "Universities across MENA are producing more graduates than ever. But top talent keeps leaving. Who's responsible for fixing this?",
      category: "Work & Careers",
      categorySlug: "work-careers",
      tags: ["Talent", "Brain Drain", "HR", "MENA"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Supply — we don't produce enough skilled talent", "Retention — we can't keep the talent we have"],
      votes: [1240, 3100],
    },
    {
      question: "Which Middle Eastern city will be the most liveable for young professionals by 2030?",
      context: "Infrastructure, cost of living, social openness, career opportunities, and lifestyle are all shifting rapidly across the region.",
      category: "Cities & Lifestyle",
      categorySlug: "cities-lifestyle",
      tags: ["Cities", "Lifestyle", "Urban", "Future"],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Dubai", "Riyadh", "Cairo", "Amman"],
      votes: [3200, 2100, 1400, 890],
    },
    {
      question: "Will Arabic-language AI models outperform GPT-4 for regional use cases within 3 years?",
      context: "Massive investments in Arabic NLP are coming from Saudi Arabia, UAE and Egypt. The question is whether they can close the capability gap.",
      category: "Technology & AI",
      categorySlug: "technology-ai",
      tags: ["AI", "Arabic", "NLP", "LLM"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Yes — regional investment will close the gap", "No — the compute and data gap is too large"],
      votes: [1870, 2430],
    },
    {
      question: "Is remote work becoming mainstream in the Gulf, or is office culture here to stay?",
      context: "Post-pandemic, global companies went hybrid. Gulf companies largely pulled people back to office. Now younger professionals are pushing back.",
      category: "Work & Careers",
      categorySlug: "work-careers",
      tags: ["Remote Work", "Gulf", "Future of Work", "Culture"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Remote/hybrid is inevitable — even in the Gulf", "Office culture will remain dominant for the next decade"],
      votes: [2100, 1650],
    },
    {
      question: "Who is building the Middle East's most important company right now?",
      context: "Head-to-head: two regional founders with very different approaches and bets on what the future looks like.",
      category: "Leadership",
      categorySlug: "leadership",
      tags: ["Founders", "Leadership", "Head-to-Head"],
      pollType: "head_to_head",
      isFeatured: false,
      isEditorsPick: false,
      options: ["The deep-tech infrastructure builder", "The consumer platform scaling across markets"],
      votes: [1580, 2240],
    },
    {
      question: "Will e-commerce in Saudi Arabia exceed $50B by 2027?",
      context: "Saudi e-commerce is growing at 30% YoY. The question is whether Vision 2030's logistics investment translates to sustained consumer spending.",
      category: "Consumer Trends",
      categorySlug: "consumer-trends",
      tags: ["Saudi Arabia", "E-commerce", "Retail", "Vision 2030"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Yes — growth trajectory is clear", "No — market saturation will slow it down"],
      votes: [1920, 820],
    },
    {
      question: "Is the Arab world experiencing a cultural renaissance or a cultural identity crisis?",
      context: "Across the region, there's unprecedented investment in arts, music, and local storytelling — but also significant debate about who gets to define Arab culture.",
      category: "Culture & Identity",
      categorySlug: "culture-identity",
      tags: ["Culture", "Identity", "Arab World", "Arts"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Renaissance — this is our moment", "Identity crisis — we're losing ourselves in the rush to modernize"],
      votes: [2640, 1890],
    },
    {
      question: "Which sector will produce the most female-founded unicorns in MENA by 2030?",
      context: "Female founders are raising record rounds across fintech, edtech, and healthtech. The landscape is shifting.",
      category: "Women in the Region",
      categorySlug: "women-in-region",
      tags: ["Women Founders", "Unicorns", "MENA", "Startups"],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Fintech", "Healthtech", "Edtech", "Consumer/Retail"],
      votes: [1450, 1100, 980, 670],
    },
    {
      question: "Should the region's major conferences and summits be in English or Arabic?",
      context: "The dominant language of business in the Gulf is still English — but many argue this systematically excludes local voices and reinforces a colonial dynamic.",
      category: "Media & Influence",
      categorySlug: "media-influence",
      tags: ["Language", "Conferences", "Arabic", "Business"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["English — it's the global business language", "Both should be equally represented"],
      votes: [980, 3240],
    },
    {
      question: "Will Saudi Arabia's football league become a top-5 league globally by 2035?",
      context: "With Ronaldo, Benzema, Neymar and multi-billion dollar investment, the Saudi Pro League is making its play for global relevance.",
      category: "Sports & Events",
      categorySlug: "sports-events",
      tags: ["Saudi Arabia", "Football", "Sports", "Investment"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Yes — quality investment will eventually translate to quality football", "No — elite global talent will prioritize competitive leagues"],
      votes: [1340, 2780],
    },
    {
      question: "What is the Middle East's single biggest opportunity over the next 10 years?",
      context: "The region is transforming at a pace that hasn't been seen in generations. Where should the world be paying attention?",
      category: "Future of the Region",
      categorySlug: "future-region",
      tags: ["Future", "Opportunity", "Vision", "MENA"],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["AI and deep technology", "Tourism and experience economy", "Manufacturing and supply chain", "Financial services and capital markets"],
      votes: [3100, 1800, 940, 1200],
    },
    {
      question: "Should MENA universities teach more in Arabic to preserve intellectual culture?",
      context: "The vast majority of research and higher education in MENA is delivered in English. Critics say this creates a two-tier intellectual class.",
      category: "Education & Learning",
      categorySlug: "education-learning",
      tags: ["Education", "Arabic", "Universities", "Culture"],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Yes — Arabic must reclaim its place as a language of knowledge", "No — global competitiveness requires English-first education"],
      votes: [2100, 1600],
    },
    {
      question: "Hot take: Egypt will produce more tech unicorns than Israel by 2030.",
      context: "Egypt's population, growing tech talent, and infrastructure investment are being bet against Israel's established VC ecosystem and exit track record.",
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: ["Egypt", "Israel", "Unicorns", "Hot Take"],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Agree — Egypt's scale will win", "Disagree — Israel's ecosystem is too mature"],
      votes: [1120, 2340],
    },
  ];

  for (const poll of pollData) {
    const [inserted] = await db
      .insert(pollsTable)
      .values({
        question: poll.question,
        context: poll.context,
        category: poll.category,
        categorySlug: poll.categorySlug,
        tags: poll.tags,
        pollType: poll.pollType,
        isFeatured: poll.isFeatured,
        isEditorsPick: poll.isEditorsPick,
        relatedProfileIds: [],
      })
      .returning();

    await db.insert(pollOptionsTable).values(
      poll.options.map((text, i) => ({
        pollId: inserted.id,
        text,
        voteCount: poll.votes[i] ?? 0,
      }))
    );
  }

  console.log(`Inserted ${pollData.length} polls`);
  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
