import { db, pollsTable, pollOptionsTable, profilesTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(pollOptionsTable);
  await db.delete(pollsTable);
  await db.delete(profilesTable);

  // ── Profiles ────────────────────────────────────────────────────────────────
  const profiles = await db
    .insert(profilesTable)
    .values([
      {
        name: "Sara Al-Rashidi",
        headline: "Redefining venture capital in Saudi Arabia",
        role: "Managing Partner",
        company: "Wadi Ventures",
        sector: "Venture & Startups",
        country: "Saudi Arabia",
        city: "Riyadh",
        imageUrl: null,
        summary: "Sara Al-Rashidi is one of the most influential voices in the Saudi startup ecosystem, having backed over 40 early-stage founders across the region.",
        story: "When Sara left McKinsey to start her own fund in 2018, very few people believed a female-led VC could thrive in Riyadh. Today, her portfolio includes three unicorns and she sits on the boards of some of the region's most exciting companies. Her thesis is simple: bet on obsessed founders solving real regional problems.",
        lessonsLearned: [
          "The region's biggest opportunity is in solving problems that global funds ignore.",
          "Relationship-building is the real currency in MENA investing.",
          "Speed of decision-making is a competitive advantage — most regional funds are too slow.",
        ],
        quote: "We're not copying Silicon Valley. We're building something the region has never seen before.",
        isFeatured: true,
        isVerified: true,
        viewCount: 12400,
        associatedPollCount: 8,
      },
      {
        name: "Omar Khalil",
        headline: "The architect of Dubai's AI infrastructure play",
        role: "Co-Founder & CEO",
        company: "NeuralBridge",
        sector: "Technology & AI",
        country: "UAE",
        city: "Dubai",
        imageUrl: null,
        summary: "Omar is building the cloud and AI infrastructure layer that powers the UAE's Vision 2031 ambitions, with over $200M raised to date.",
        story: "A former Microsoft engineer who grew up in Alexandria, Omar saw an infrastructure gap in the region that no global cloud provider was solving. He moved to Dubai in 2019, raised a seed round in 90 days, and never looked back. NeuralBridge now employs 340 people across 8 countries.",
        lessonsLearned: [
          "Infrastructure is boring until it's not — then it's everything.",
          "Hire people who argue with you. Yes-men build mediocre companies.",
          "The Middle East's talent problem is a marketing problem. The talent exists.",
        ],
        quote: "Every nation that controls its own AI infrastructure will define its own future. That's why this matters.",
        isFeatured: true,
        isVerified: true,
        viewCount: 9800,
        associatedPollCount: 12,
      },
      {
        name: "Lina Mansour",
        headline: "Turning Jordan's creative economy into a global export",
        role: "Founder",
        company: "Studio Bilad",
        sector: "Media & Content",
        country: "Jordan",
        city: "Amman",
        imageUrl: null,
        summary: "Lina built Amman's most influential creative agency from a bedroom studio to a 60-person team producing content for brands across 14 countries.",
        story: "Lina started Studio Bilad with $3,000 and a camera she saved for two years to buy. She believed that Arab storytelling deserved world-class production values. Five years later, her studio has won 22 regional awards and her content has been watched over 800 million times across platforms.",
        lessonsLearned: [
          "Authenticity is the only differentiator that doesn't expire.",
          "Never apologize for creating in Arabic. It's your biggest advantage, not your limitation.",
          "The diaspora is your distribution network. Use it.",
        ],
        quote: "We're not 'emerging.' We've been here. The world is finally looking.",
        isFeatured: true,
        isVerified: true,
        viewCount: 8200,
        associatedPollCount: 5,
      },
      {
        name: "Khalid Al-Faraj",
        headline: "Saudi Arabia's most debated leadership voice",
        role: "CEO",
        company: "Mawjoud Group",
        sector: "Leadership",
        country: "Saudi Arabia",
        city: "Jeddah",
        imageUrl: null,
        summary: "Khalid has built one of the GCC's largest family business conglomerates while being one of the most outspoken voices on leadership reform in the Arab world.",
        story: "Inheriting a struggling family business at 28, Khalid transformed it into a 14-company group over 15 years. He's now one of the loudest advocates for professionalizing Arab family businesses and breaking the culture of nepotism that he says held back the region for decades.",
        lessonsLearned: [
          "Merit must win over loyalty — in family businesses and in nations.",
          "Your reputation is built in the downturns, not the booms.",
          "Leaders who don't read are managing on borrowed time.",
        ],
        quote: "The Arab world has incredible ambition and terrible systems. Fix the systems.",
        isFeatured: false,
        isVerified: true,
        viewCount: 7100,
        associatedPollCount: 9,
      },
      {
        name: "Nora Hamdan",
        headline: "Making fintech accessible to 100M underbanked Arabs",
        role: "Co-Founder & COO",
        company: "Fulus",
        sector: "Finance",
        country: "Egypt",
        city: "Cairo",
        imageUrl: null,
        summary: "Nora co-founded Fulus to bring financial inclusion to the 100 million Arabs without bank accounts, raising $45M Series B in 2025.",
        story: "Growing up watching her parents struggle with the informal money economy, Nora always believed that access to basic financial services was a right, not a privilege. She studied economics in Cairo, got an MBA in London, and returned home with a mission. Fulus now serves 2.3 million users across Egypt and Jordan.",
        lessonsLearned: [
          "The biggest market opportunity in MENA is the one that global VCs can't underwrite.",
          "Regulatory relationships are a competitive moat, not a burden.",
          "Trust is the product when you're serving people who've been failed by institutions.",
        ],
        quote: "Financial exclusion is a policy choice. So is inclusion.",
        isFeatured: false,
        isVerified: true,
        viewCount: 6300,
        associatedPollCount: 6,
      },
      {
        name: "Tariq Al-Sayed",
        headline: "Building Qatar's quantum computing ecosystem",
        role: "Chief Scientist",
        company: "Qatar Computing Research Institute",
        sector: "Technology & AI",
        country: "Qatar",
        city: "Doha",
        imageUrl: null,
        summary: "Tariq leads QCRI's flagship quantum initiative and has published 87 papers that are shaping how the Middle East approaches deep tech.",
        story: "Tariq was the first Qatari to complete a PhD in quantum computing. He turned down offers from IBM and Google to return to Doha, believing that the Gulf needed its own research IP, not just licensing deals. He's now building a team of 120 researchers and training the next generation of Arab scientists.",
        lessonsLearned: [
          "The region's brain drain is a story we tell ourselves. The talent returns if the opportunity is real.",
          "Publish or perish is for academics. Build or perish is for us.",
          "Basic research is infrastructure. Stop treating it like a luxury.",
        ],
        quote: "Nations that don't invest in curiosity will always buy the future from those who do.",
        isFeatured: false,
        isVerified: true,
        viewCount: 5800,
        associatedPollCount: 4,
      },
      {
        name: "Maya Rifai",
        headline: "The Lebanese entrepreneur rebuilding from zero",
        role: "Founder",
        company: "Zaman",
        sector: "Retail & Consumer",
        country: "Lebanon",
        city: "Beirut",
        imageUrl: null,
        summary: "Maya launched Zaman in the aftermath of the Beirut explosion, creating a sustainable lifestyle brand that ships to 40 countries.",
        story: "Maya lost her apartment, her office, and her first business in the 2020 Beirut explosion. Six months later, she launched Zaman from a co-working space with $8,000 in savings. What started as handmade Lebanese crafts has evolved into a global brand that celebrates Arab craft traditions with modern design sensibility.",
        lessonsLearned: [
          "Crisis reveals what actually matters in a business model.",
          "Diaspora customers are your most loyal — they're buying identity, not just products.",
          "Don't wait for stability. Build despite the chaos.",
        ],
        quote: "Beirut has been rebuilt seven times. This is just the eighth.",
        isFeatured: false,
        isVerified: true,
        viewCount: 5200,
        associatedPollCount: 3,
      },
      {
        name: "Ahmed Al-Balushi",
        headline: "Oman's most ambitious climate entrepreneur",
        role: "Co-Founder & CEO",
        company: "GreenGulf Energy",
        sector: "Energy",
        country: "Oman",
        city: "Muscat",
        imageUrl: null,
        summary: "Ahmed is building the Gulf's first vertically integrated green hydrogen company, backed by sovereign funds from three GCC nations.",
        story: "Ahmed spent 10 years at Shell before deciding he could do more outside. He raised $120M to build the infrastructure that will eventually power the decarbonization of Gulf industry. His bet is that Oman's geography and sunlight make it the ideal hub for green hydrogen exports to Europe by 2030.",
        lessonsLearned: [
          "Energy transition in the Gulf is not idealism — it's economics. Follow the money.",
          "Sovereign fund backing changes everything: speed, credibility, distribution.",
          "The cleanest thing you can do is be honest about timelines.",
        ],
        quote: "We built our wealth on oil. We'll build our future on sunshine.",
        isFeatured: false,
        isVerified: false,
        viewCount: 4100,
        associatedPollCount: 2,
      },
    ])
    .returning();

  console.log(`Inserted ${profiles.length} profiles`);

  // ── Polls ────────────────────────────────────────────────────────────────────
  const pollData = [
    {
      question: "Your job will still exist in 5 years. Be honest.",
      context: "AI isn't coming for jobs — it already has. The question is whether you've accepted it yet.",
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: ["AI", "Jobs", "Future of Work", "Career"],
      pollType: "multiple_choice",
      isFeatured: true,
      isEditorsPick: true,
      options: ["Yes, I'm irreplaceable", "Probably not and I'm doing nothing about it", "Probably not but I have a plan", "I genuinely don't know"],
      votes: [1200, 2800, 1900, 3100],
    },
    {
      question: "The most dangerous thing AI did wasn't take jobs — it exposed how many jobs were already pointless.",
      context: "Millions of roles existed because no alternative existed. Now there is one.",
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: ["AI", "Work", "Hot Take"],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Brutally accurate", "Too harsh — most jobs have real value"],
      votes: [4200, 1100],
    },
    {
      question: "Would you rather be managed by an AI or a mediocre human manager?",
      context: null,
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: [],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Give me the AI", "I'll take the human, flaws and all"],
      votes: [3800, 1400],
    },
    {
      question: "If AI replaces your role, whose fault is it?",
      context: null,
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Mine — I didn't upskill fast enough", "My company — they didn't train or warn me", "Nobody's — this was always going to happen", "The government — they should have regulated this"],
      votes: [2100, 1600, 2800, 900],
    },
    {
      question: "Wasta still beats talent in this region. Agree?",
      context: "You can be the best in the room and still lose to someone's cousin. Has anything actually changed?",
      category: "Work & Careers",
      categorySlug: "work-careers",
      tags: ["Wasta", "Talent", "Culture", "Careers"],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["100% still true", "Getting better but slowly", "Depends on the country", "It's a myth — merit wins if you're good enough"],
      votes: [3400, 2100, 1800, 600],
    },
    {
      question: "The real brain drain isn't people leaving — it's people staying and checking out.",
      context: "Physically present. Emotionally gone. Building nothing. The quiet resignation nobody talks about.",
      category: "Work & Careers",
      categorySlug: "work-careers",
      tags: [],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: false,
      options: ["This is the actual crisis", "No — people leaving is still the bigger problem"],
      votes: [3900, 1200],
    },
    {
      question: "Most 'founders' in this region are consultants with a pitch deck. Change my mind.",
      context: null,
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: ["Founders", "Startups", "Hot Take"],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Can't — this is painfully accurate", "Wrong — real builders are everywhere, just underreported"],
      votes: [2800, 1900],
    },
    {
      question: "The next unicorn from this region will come from...",
      context: null,
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Cairo", "Riyadh", "Dubai", "Somewhere nobody's watching yet"],
      votes: [2100, 2400, 1800, 3200],
    },
    {
      question: "LinkedIn in the Arab world is just a brag board. Nobody posts their failures.",
      context: null,
      category: "Culture & Identity",
      categorySlug: "culture-identity",
      tags: ["LinkedIn", "Culture", "Authenticity"],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Facts — it's completely performative", "Disagree — it's improving", "Same everywhere, not just here"],
      votes: [4100, 600, 1800],
    },
    {
      question: "Arab parents would rather their kid be a doctor than a founder. Can you blame them?",
      context: "Founding a company in this region means navigating systems designed for established players. The risk is real.",
      category: "Culture & Identity",
      categorySlug: "culture-identity",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Can't blame them — the odds are brutal", "This mindset is exactly why we fall behind", "It's changing with the new generation"],
      votes: [2200, 2800, 1900],
    },
    {
      question: "We're becoming obsessed with looking successful instead of actually being successful.",
      context: null,
      category: "Culture & Identity",
      categorySlug: "culture-identity",
      tags: [],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: false,
      options: ["This is the defining disease of our generation", "Disagree — ambition drives real outcomes too"],
      votes: [3600, 1100],
    },
    {
      question: "The diaspora built half of what the Middle East is proud of — and gets none of the credit.",
      context: null,
      category: "Culture & Identity",
      categorySlug: "culture-identity",
      tags: [],
      pollType: "binary",
      isFeatured: false,
      isEditorsPick: false,
      options: ["True — and it needs to change", "False — the credit is there if you look"],
      votes: [3800, 900],
    },
    {
      question: "Egypt is one bad IMF negotiation away from something really ugly.",
      context: null,
      category: "Finance & Economy",
      categorySlug: "finance-economy",
      tags: ["Egypt", "IMF", "Economy", "Crisis"],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Agree — the fundamentals are broken", "Disagree — Egypt always finds a way", "It's already ugly, we just aren't saying it"],
      votes: [2400, 1200, 2900],
    },
    {
      question: "Dubai property in 2025 — still inflating or finally about to correct?",
      context: null,
      category: "Finance & Economy",
      categorySlug: "finance-economy",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Still inflating — demand is structural", "Correction is coming within 2 years", "Already correcting, quietly"],
      votes: [1800, 2100, 1400],
    },
    {
      question: "In 10 years, the most valuable skill in the Middle East will be...",
      context: null,
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: true,
      options: ["Knowing how to work with AI", "Human judgment and emotional intelligence", "Arabic fluency at a professional level", "Knowing the right people"],
      votes: [3200, 2400, 1100, 1800],
    },
    {
      question: "A 22-year-old in Cairo with a laptop has more opportunity than their parents ever did. True or false?",
      context: "The internet removed gatekeepers. But it also created new ones. Algorithms, English fluency, access to capital.",
      category: "AI & The Future",
      categorySlug: "ai-future",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["True — the tools exist, excuses don't", "False — structural barriers are worse than ever", "True for some, completely false for most"],
      votes: [2100, 1600, 3400],
    },
    {
      question: "Saudi money changed the Gulf startup scene. Not always for the better.",
      context: null,
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: [],
      pollType: "hot_take",
      isFeatured: false,
      isEditorsPick: false,
      options: ["Agree — it inflated valuations and created dependency", "Disagree — it unlocked a decade of real growth"],
      votes: [2600, 1800],
    },
    {
      question: "If your startup needs a government contract to survive Year 1, is it really a startup?",
      context: null,
      category: "Startups & Venture",
      categorySlug: "startups-venture",
      tags: [],
      pollType: "multiple_choice",
      isFeatured: false,
      isEditorsPick: false,
      options: ["No — that's a services business with a deck", "Yes — working with government is just a distribution strategy", "Depends entirely on the sector"],
      votes: [2200, 1400, 2800],
    },
  ];

  for (const poll of pollData) {
    const [inserted] = await db
      .insert(pollsTable)
      .values({
        question: poll.question,
        context: poll.context,
        category: poll.category,
        categorySlug: poll.categorySlug,
        tags: poll.tags,
        pollType: poll.pollType,
        isFeatured: poll.isFeatured,
        isEditorsPick: poll.isEditorsPick,
        relatedProfileIds: [],
      })
      .returning();

    await db.insert(pollOptionsTable).values(
      poll.options.map((text, i) => ({
        pollId: inserted.id,
        text,
        voteCount: poll.votes[i] ?? 0,
      }))
    );
  }

  console.log(`Inserted ${pollData.length} polls`);
  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
